on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: meta-introspector/checkout@main
    - name: self test action
      uses: ./
